### ISSUE TITLE
Solving IDE indexing question

### ISSUE THREAD

**Issue by jonnyzzz** [Microsoft/GVFS#1]
Thank you for the presentation at #gitmerge 2017. It was great.

I'm wondering how do you indent to solve the intents from IDE to fetch all files to index sources. Similarly, compilation may require too much files to be fetched.

**Comment by sanoursa** [comment]
That's a great question. Typically, you're going to use an IDE to open the set of files you're going to work with, not every file in the repo. So in that sense, the IDE is doing you a favor by opening all of those files, because it is hydrating the exact set of files that you care about.

The same is true of building, if you build some subtree of the repo, you'll be hydrating all of those files and you can then work with them locally. 

The first build, or the first time you open in the IDE, will be slower than normal because of the extra latency of downloading those files, but then from then on those files will be on your local system.

**Comment by yangm97** [comment]
Instead of hoping that the IDE will “hydrate” the files, GVFS could, optionally, fetch the latest commit automatically.

**Comment by jonnyzzz** [comment]
This approach would likely to force anyone to have a small project under the huge mono-repo. Do you use it this way for Windows or VSTS repos?

I was curious if you try sharing IDE/compiler caches/indexes associated with each revision or globally somewhere on the backend. This would let users to fetch (or query) caches instead of wasting time downloading too many files locally

**Comment by kolodny** [comment]
It seems silly to have to download a large file, only to have it indexed and then discarded. I really wish that IDE's would expose the indexing component to run remotely and send the serialized index over the wire

**Comment by jonnyzzz** [comment]
@kolodny Silly? Right you are. But how many IDEs (not just a vi) around does use such bright ideas? :)

I was actually writing exactly the same thing. To share caches, instead of rebuilding them. But, this would make an IDE to be a server-dependent too. But in the context of GVFS it's not an issue any more.

**Comment by sanoursa** [comment]
@yangm97 Very true. Smart prefetching of blobs is something we've talked a lot about, we just haven't gotten to it yet. We do have the ability to do manual prefetching though, you can simply type "gvfs prefetch repo-relative-path" to prefetch all the blobs for a given path that you know you're going to use.

@jonnyzzz We have a lot of devs in Windows, and they different tools and different workflows across the board. That said, the 95% use case is that they will only build a small subset of files within the repo, whether that's with Visual Studio or with command line build tools. We don't really rely on an IDE to download files for you, my point was just that when VS starts doing a background compile, it's not hurting you because it's in effect prefetching files that you would have built anyway.
