### ISSUE TITLE
NUnit 3.10.0-dev-05190 no longer on Nuget

### ISSUE THREAD

**Issue by Kleptine** [Microsoft/GVFS#109]
I tried building the solution, but it looks like the specific version of NUnit isn't available anymore on Nuget. The build errors out with 
![image](https://user-images.githubusercontent.com/1078792/41722870-864677ac-751e-11e8-85f4-69baeee74fc7.png)

Presumably 3.10.0 should work?

**Comment by sanoursa** [comment]
Sorry for the trouble here. We've already fixed both of these issues, but the code hasn't made it out yet.

For NUnit, we were relying on a dev release with some bug fixes for parallel tests. That package has expired, but the latest official release (3.10.1) has all the bug fixes we need.

For LibGit2, we did have a private internal package, but not really for any great reason. We've already dropped that in favor of the LibGit2Sharp.NativeBinaries package on nuget.org.

Both of these will be fixed with our next push, and this whole class of issue will go away soon as well. We're maybe a week or two away from completing https://github.com/Microsoft/GVFS/issues/77, which moves our own daily work into this repo on GitHub and will avoid this sort of staleness.

As for your final question - I'd love to hear your thoughts on how you will use this for artists. What are your file locking needs? How do you envision tweaking GVFS to support that?

**Comment by sanoursa** [comment]
Actually I'd like to suggest a separate issue to discuss artist-focused design changes. This is an area I'm very interested in, so I'd love to hear your thoughts.

I'll close this issue as soon as we do our next push.

**Comment by Kleptine** [comment]
Great to hear! :) I'll open a separate issue regarding file locking and GVFS.

**Comment by sanoursa** [comment]
We have upgraded to the latest official NUnit release.
