### ISSUE TITLE
Hydrated?

### ISSUE THREAD

**Issue by szeder** [Microsoft/GVFS#11]
What exactly is a "fully hydrated repo"?  There is no such thing in Git terminology.

Please use proper terminology in the Readme and elsewhere.

**Comment by Dessix** [comment]
There is no such thing in Git terminology because Git itself doesn't have the concept of getting a partial repository that still functions as a full copy. Hydration implies that the file's contents are available locally, while most files are simulated as being there, and only files where the contents are needed to perform the actions become "hydrated".

**Comment by sanoursa** [comment]
To hydrate generally means to fill something with contents. In GVFS, what we mean is that when you first enumerate a directory, what you see in the listing looks like normal files, but they don't have any contents in them. When you open a file for the first time, we go and download its contents and hydrate the file on disk so that from then on, it's a normal file with full contents.

**Comment by szeder** [comment]
If you want to say "git and tools see a fully functioning repo" in the Readme's second sentence, then just do so.
