### ISSUE TITLE
Unable to unmount gvfs unable to delete files

### ISSUE THREAD

**Issue by michalejoye** [Microsoft/GVFS#111]
We were testing GVFS for testing but now the testing is over with, we are unable to delete the files.
We have tried to unmount but we get this error:
Unmounting...Failed. Run 'gvfs log C:\UnrealEngine' for more info.
Unable to connect to GVFS.Mount

**Comment by michalejoye** [comment]
We had to restart the computer to get the GVFS.Mount.exe from running. Does gvfs work with git ui clients like git extensions?

**Comment by sanoursa** [comment]
Any git clients/extensions that shell out to git.exe will work as normal (assuming they're shelling to the installed git.exe, not some private version). Tools that use libgit2 or other means of directly accessing the .git folder will not work since they do not understand the extensions we've made to git.
