### ISSUE TITLE
Performance Question - Writes?

### ISSUE THREAD

**Issue by putztzu** [Microsoft/GVFS#114]
Sorry that this is probably more suited to a discussion forum rather than submitted as an "Issue" but it seems that usual discussion forums don't exist for this project because it's still small and new enough it might not yet be trying to find Users and is more focused on Development.

I'm interested in looking at GVFS for possible use in common Infrastructure scenarios rather than as a Developmental Repository technology. I do find features in GVFS that were created to improve usability for very large collections of files could also be beneficial for some of the scenarios I want to support.

I'd be curious if there has been any attention paid to **write performance**, primarily
- Whether write-backs are supported or implemented
- Whether lazy writes are supported' or implemented

And, if there has been any attention paid to write performance, whether there has been any testing

Am curious also if there is a recommended blog somewhere that describes how the GVFS implementation is supposed to be implemented in a manner similar to FUSE unless the only important concept is that it's being implemented in User Space and not in kernel space. My experience with FUSE generally has been to deploy a FS on raw blocks rather than an as an overlay which is what GVFS appears to be.

Thx.

**Comment by sanoursa** [comment]
Filing issues for questions/discussions is totally fine!

From what you're describing, I think you're actually more interested in the ProjFS driver rather than GVFS itself.  ProjFS is in early stages of being released - so while the driver itself is now available on the latest Windows release, the APIs and documentation will not be available until the next Windows release. 

That said, I can answer most of your questions about it here. The thing to understand about ProjFS is that it is not a general equivalent to FUSE. It is designed for a very specific use case where you have a remote tree that you want to project into the local file system. It uses the local file system as a cache of the remote tree and also as the source of truth of all writes, overlayed on top of that cache.

As a result, ProjFS only calls back to the provider process (the user mode process) when it needs to hydrate a file. It _does_ let the provider know when a write occurs, but it _does not_ send the data of the writes to the provider, because there is no need for it. The writes happen directly in the NTFS file system. Similarly, all reads happen directly in the NTFS file system, because after the first time hydration occurs, the data is now present and there is no more need for interaction with the provider.

This reason for these design choices is actually that read and write performance are a primary goal of this system (and coincidentally why we can't use FUSE). We have lots of testing around the performance of reads and writes, and ensuring that there is very minimal overhead on reads/writes compared to a non-virtualized NTFS path.

The best documentation on this whole approach is currently available at https://docs.microsoft.com/en-us/azure/devops/git/gvfs-architecture. I am also working on a blog post more focused on ProjFS, and we will very soon publish a much simpler provider implementation using the ProjFS API, which should be a much easier sample to follow than the GVFS codebase.

**Comment by putztzu** [comment]
Thx! 
Your blog article isn't one I found, looks like a good foundation read.
That's an interesting architecture, your virtual file system doesn't appear to be its own independently separate layer but implemented as an extension of NTFS. That certainly appears to imply near zero if any latency compared to normal NTFS operations. Will read more about how metadata is stored and written, I assume that is not tightly coupled? ie. metadata is queued and written lazily.

**Comment by sanoursa** [comment]
Re: metadata - no nothing is written lazily, because that would not be resilient to a crash or power loss. Both the PrjFlt driver and GVFS itself are careful to persist state in a way that is robust to power loss. That said, we had to design GVFS to do that very efficiently to avoid locking up file system perf. E.g. if we decide, during a callback from the driver, that we have to do some expensive IO, we first write a record onto disk (and flush it) indicating what the work is, then unblock the driver and actually do the work in the background.

Closing for now, but please feel free to file more questions as and when you have them.
