### ISSUE TITLE
Use open formats please

### ISSUE THREAD

**Issue by 4twilight** [Microsoft/GVFS#12]
Hey, how you suppose the others will access the information in proprietary formats, like this:
https://github.com/Microsoft/GVFS/blob/master/GvFlt_EULA.docx

Majority of Users don't have MS office package installed.
Please respect others freedom and Community you're trying to work with.

**Comment by sanoursa** [comment]
I've actually already sent a request to the GvFlt team to provide their EULA in a format that will render directly in GitHub, so that you don't have to download it to read it.

**Comment by darkstar** [comment]
@4twilight Here is a nice google search to help you post this request to all the other projects that use docx files in their repo: https://www.google.de/search?q=site:github.com+ext:docx

You might want to open a github issue for each of them as well, since they're using such an anti-Community file format

**Comment by IanET** [comment]
In the meantime, there are a bunch of non-microsoft viewers for docx files. I just tried drive.google.com and it worked great. See attached. 
[GvFlt_EULA.pdf](https://github.com/Microsoft/GVFS/files/814618/GvFlt_EULA.pdf)

**Comment by ExE-Boss** [comment]
Actually, docx is an open [ECMA-376](https://www.ecma-international.org/publications/standards/Ecma-376.htm) and [ISO/IEC 29500](https://www.iso.org/standard/71691.html) specification, which is built on the ZIP and XML formats.
