### ISSUE TITLE
Releases - Download executables Question

### ISSUE THREAD

**Issue by putztzu** [Microsoft/GVFS#122]
In every release, there are two executables...

Want to verify appearances...

The first executable (Not the Setup) looks like it's just git for Windows, does not include GVFS - correct?
The second executable (Setup) likely installs GVFS - correct?

And, it appears to me that there are no special directives about configuring locations, these two executables install git and GVFS system-wide so that wherever a git repo is setup (init), GVFS functionality is automatically an extension of every git repo that is set up - Correct?

And, that would apply also to setting up own git servers?

TIA.

**Comment by sanoursa** [comment]
That is correct, every GVFS release also has a corresponding Git for Windows release, and you need to install both.

GVFS is not automatically an extension of every git repo. If you want the benefits of GVFS, you must clone the repo using `gvfs clone` instead of `git clone`. After you have cloned, you can then use normal git commands inside the repo.
