### ISSUE TITLE
How to create new GVFS repository?

### ISSUE THREAD

**Issue by putztzu** [Microsoft/GVFS#125]
Apparently this topic has been overlooked in public documentation and --help.

Documentation describes how to clone a regular git to a GVFS repo.
Documentation describes mounting and unmounting a GVFS repo, which seems to be an additional requirement beyond managing a normal git repo.

But, the documentation appears to be silent how to create a new GVFS repo.
Will "git init" create a GVFS repo if GVFS is already installed on the system?
Or, is something like "gvfs init" required despite no documentation?
Or, is this something that does not yet exist, and for now the only way to create a GVFS repo is to do the conversion using the clone command?

Thx.

**Comment by sanoursa** [comment]
There really isn't any notion of a "GVFS repo" as its own concept. GVFS is just a tool for working with an existing, large Git repo. The assumption is that you have an already-created Git repo on a GVFS-enabled server, and then you use `gvfs clone` to create a local virtual projection of it. Because of that, we haven't created a `gvfs init` command because there wouldn't be much use for one.

If you're wondering how to create the large repo in the first place, that all depends on what your starting conditions are. Do you have an existing, large codebase that you're migrating? Do you have a bunch of existing Git repos that you're looking to stitch together? Do you have a single Git repo that is just starting to get too big to handle? We don't have any stock advice yet, but if you offer up some details, we'd be happy to help you think through the options.

**Comment by putztzu** [comment]
Thx,
The idea is to start with something new that will grow.
So, this isn't a situation looking to solve a problem that already exists (a git repo so large it's bursting at the seams), but a forward-looking provisioning procedure... Small today but set up so that no future action should be required.

**Comment by sanoursa** [comment]
Makes sense. In your case, you would need to have one person use normal git to create and push the repo. Once it's up there, anyone can clone it with normal `git clone` or with `gvfs clone`.
