### ISSUE TITLE
fatal: CRLF conversions not supported when running under GVFS

### ISSUE THREAD

**Issue by boltomli** [Microsoft/GVFS#18]
When I gvfs clone a repo, the error happens:

fatal: CRLF conversions not supported when running under GVFS

I'm on a Windows client, of course.

**Comment by sanoursa** [comment]
Yes this is by design. As described in the readme, there are two constraints on a repo that you want to clone with GVFS: 1) it can't enable any clean or smudge filters (CRLF conversion is a built in filter) and 2) it must have a .gitattributes file in the root (ideally including the line "* -text" to disable CRLF conversion)

I have a document coming out very soon that goes into some depth about why we made various design choices, including this one. As a preview on this issue: when we're enumerating a folder for which we don't yet have all the files, we figure out what the child items should be by examining the git tree object for the folder we're enumerating. The tree gives us the blob id and the name of each child, but not its size, but NTFS requires us to specify both a name and a size for each chlid. The way we get that size is that we call the new REST endpoint /gvfs/sizes and ask it for the sizes for the blob ids of all the files in that folder. Then later on, whenever you try to open one of those files, we'll call the /gvfs/objects endpoint to get its contents, write them into the file, and then from then on it's a normal file that you can interact with however you like.

The trick is, the contents that we write into the file must match the size that reported for it when we enumerated. And filters that make really hard (sometimes impossible) because they can arbitrarily transform the contents of a blob before they write it into a file.

So for now, we've made the choice to disable all filters (the behavior is enforced in Git, but only when running on a GVFS repo). Moving forward, we can think about how to enable some of the builtin filters, though it's not an easy problem to solve (e.g. you might enable CRLF conversion via the .gitattributes file, in which case the server can detect it and update its response to /gvfs/sizes appropriately, or you might enable CRLF conversion via a global config setting, in which case the server has no idea). Though we'll never be able to support arbitrary filters, because the server has no hope of knowing how those filters can transform the file contents.
