### ISSUE TITLE
Question - Does GVFS replace NTFS?

### ISSUE THREAD

**Issue by Korporal** [Microsoft/GVFS#25]
Just trying to get a broad idea of how GVFS operates. Is it a replacement file system for NTFS? I mean does it do what NTFS does but include additional functionality? or does it replace NTFS but lose some NTFS functionblaity?

**Comment by SamuelEnglard** [comment]
Works on top of something like NTFS

**Comment by sanoursa** [comment]
GVFS uses a file system filter driver called GvFlt, which is a filter driver that sits on top of NTFS. This allows us to inject enumeration results and file contents on demand, but then allow NTFS itself to handle everything else.

**Comment by fpqc** [comment]
@sanoursa Is GvFlt the basis for the new onedrive functionality announcd in the FCU?  It looks almost identical =).

**Comment by magol** [comment]
Is it any functional differens between  GvFlt and [Dockan](https://github.com/dokan-dev/dokany)?

**Comment by Rondom** [comment]
Given that GvFlt is a closed source chocolatey package there is not much source to peek into except GVFS itself. MS promised to post a blog article about it's mode of operation "soon".

From the scarcely available information I deduce that it is rather a "filter driver in userspace" than filesystem in user space. They did not seem to want to pay the overhead of a FUSE mount for their product, so they went with a filter driver that forwards the request to NTFS of the file is available locally.

This is cool in its own right, but one cannot replace the other, it seems.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by fpqc** [comment]
@Rondom No, it's a filter driver in kernel space (gvflt.sys).  That's why they were talking about performance and context switching.  If the filter driver were in userspace, you wouldn't get any improvement in performance over a generic FUSE implementation.

You can see it in this documentation page referenced as a kernel filesystem filter driver (which is why its extension is .sys rather than .dll):

https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/allocated-altitudes

It seems simple enough to understand: The GVFS implementation above and available in this respository is basically all of the code that doesn't need to live in kernelspace, and the GvFLT code implements the kernel-side stuff, which probably has to do with fast switching between pulling from disk and pulling from the remote repositories.  The code is probably not very interesting to Linux or OSX developers since a lot of it is probably very Windows-specific, dealing in particular with the kernel-exposed parts of the NTFS driver and kernel networking API in order to reduce context switching to a minimum.

So the idea is once the request for the file is issued from userspace with NtOpenFile, the GvFLT driver intercepts this call, pulls the file from 1.) cache in memory 2.) disk or 3.) the remote repository, and returns it transparently to the caller of NtOpenFile.  

The gist of why why it lives in kernel space rather than userspace is that it reduces the number of expensive context switches (from user mode to kernel mode and vice-versa) vs a FUSE-style implementation, where for each file, you would have to jump into the FUSE kernel driver, up into userspace, back down into the FUSE driver, then back into the kernel for resolution of the system call (if I understand how FUSE works).  

If you read the posts by the developers, they mention that the additional context switches from FUSE-style implementations slowed things down a lot and did not produce acceptable performance from the internal Microsoft perspective (GVFS arising from Microsoft's own decision to move completely over to GIT from their previous solution).  The details of how the Gvflt driver are very Windows-specific, although it might be that their caching strategies and some design elements might be relevant to implementations on other platforms.

**Comment by Rondom** [comment]
Thanks for the detailed explanation. I was not clear. The "it" in the second paragraph was referring to GVFS not to GvFlt. So, GvFlt is a filter driver that enables implementing filter driver functionality in user space, of which GVFS is an example. So, what I meant is that you can think of GvFlt as "filter driver in user space" (as opposed to filesystem in userspace). Please correct me, if I am wrong on this.

(Oh, and I typed that message on my mobile this morning not being aware that the email came from the GVFS repo, thinking it was from another repo. Otherwise I would have kept my mouth shut and let the people here that have more of a clue talk :smile:  )

**Comment by fpqc** [comment]
FUSE is just an API to talk to a driver that allows you to implement filesystem logic in a userspace library. It looks like GvFLT moves more of that logic directly into the kernel space, ostensibly sacrificing some flexibility for performance. 

I don't know if GvFLT has been documented well enough to see directly if you could e.g. write a generic FUSE wrapper around it.

What is likely the case is that the associated gvflt service has some kind of COM interface that provides an API that gets used in the GVFS sourcecode here, and that API will let you program against the driver without having to make direct IOCONTROL calls to it.
