### ISSUE TITLE
Path-Based Read Access

### ISSUE THREAD

**Issue by joelthompson** [Microsoft/GVFS#30]
If you move to a monorepo, the size of the repository tends to grow very large, and it presents a security challenge -- you might only want to let a small number of people access the more sensitive parts of your codebase. GVFS is designed to solve the first problem, and it seems like a good foundation to solve the second -- if you're not allowed to read a particular file, then the GVFS server simply will refuse to serve it to you.

**Comment by sanoursa** [comment]
We made a decision early on that we did _not_ want to change Git's security model with GVFS. With Git, you either get access to a whole repo, or you don't, and it's no different with GVFS.

Really, GVFS is not the right tool to enforce permissions anyway, because its only purpose is to improve local performance. A user could still go view the repo in the web, or just run a "git clone" on it and wait the hours required to clone, and GVFS can't help with those issues.
