### ISSUE TITLE
GVFlt Service is not running

### ISSUE THREAD

**Issue by zhuangbiaowei** [Microsoft/GVFS#34]
I build & setup，without any errors。

In git bash, run gvfs clone URL,got message:

Error: GVFlt Service is not running. To resolve, run "sc start gvflt" from an admin command prompt

run: sc start gvflt，got message:

[SC] StartService FAILED 127:
The specified procedure could not be found.

**Comment by rodwiddowson** [comment]
Typically this is because one of the executables is targetted against a too-new version.

Check the target (target, TargetPlatform, PlatofrmToolset) in anything you are building.

If nothing leaps out look at each of the executables involves (.sys, .dll, .exe) with Depends.exe (available in old SDKs, no idea where it is these days).  Do this on your target machine.  That should get you to the next stage

**Comment by fpqc** [comment]
The Gvflt service is the protected light system service attached to the Gvflt kernel driver (gvflt.sys), which needs to be obtained from Microsoft, since all drivers must be signed.

You need to install the NuGet package for GvFLT 

https://www.nuget.org/packages/Microsoft.GVFS.GvFlt/0.17523.1-preview

I'm not sure if this is signed, but if it isn't it means you must also put your system into testsigning mode for it to work.

**Comment by zhuangbiaowei** [comment]
In C:\Program Files\GVFS\Filter, I run:
rundll32.exe setupapi.dll InstallHinfSection DefaultInstall 132 .\gvflt.inf

but, can't got any errors.

**Comment by zhuangbiaowei** [comment]
@fpqc I already download Microsoft.GVFS.GvFlt/0.17523.1-preview

so...I not know.

**Comment by zhuangbiaowei** [comment]
In the event viewer, I see the system log as follows:

Information(Application Popup):

The description for Event ID 26 from source Application Popup cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

**gvflt.sys cannot find ntoskrnl.exe PsGetHostSilo**

the message resource is present but the message is not found in the string/message table

**Comment by zhuangbiaowei** [comment]
I found the reason, because my Windows 10 version is 1511.
And PsGetHostSilo need to support Windows 10, version 1607......


so... At README.md, You should give a clear hint: Windows 10 version 1607 or later!

**Comment by fpqc** [comment]
It says that. It says use 1703 or later!!

**Comment by sanoursa** [comment]
That is correct, the readme says that GVFS requires Windows 10 Creators Update, which is 1703. I'm happy to add the version number there too, as another clue.

**Comment by sanoursa** [comment]
The readme is now more specific about the Windows version number
