### ISSUE TITLE
Question - Is Git-LFS (Large File Storage) supported?

### ISSUE THREAD

**Issue by GordonRudman** [Microsoft/GVFS#37]
Well done on a great concept! 
I look forward to trying it out.

GVFS will be great for my needs if it also supports very large files.
1. Is the combination of GVFS and VSTS-LFS supported yet?
2. Can I specify my own LFS Store / Server for storing the large files?
3. Can the LFS Store be local storage, like 'directly' on hard drives / network storage?

**Comment by sanoursa** [comment]
GVFS currently requires that you disable all clean/smudge filters in your repo, which means that LFS is not supported right now because it uses filters. We do have conversations in progress about how to enable filters, but I don't have an ETA on that yet. 

The core issue is that when we enumerate a virtual file, the size that we claim for it must be accurate - but filters like LFS intentionally manipulate the contents of a file relative to what's stored in the git blob, making our virtual size incorrect, and therefore making the file look like it has not enough or too many bytes when you open it. It's a solvable but tricky problem, and we still need to think more about how to make it work.

That being said, GVFS itself does a pretty good job of handling large files, since it only downloads the files that you actually use.
