### ISSUE TITLE
Squash already downloaded but unused files

### ISSUE THREAD

**Issue by piranna** [Microsoft/GVFS#46]
Add an option to remove (squash) files not used recently and that are already on the remote GIT repository. This can be done based on some rules, like storage is full or files untouched for some months or so. This can allow for a transparent Dropbox-like or remote cache-like filesystem without wasting a lot of local space or when it's not available (for example, several tablets using a multi-terabyte home NAS).

**Comment by stefanes** [comment]
Or add a filter option to the `dehydrate` command to dehydrate all files not touched in x days.

**Comment by piranna** [comment]
I would prefer that the dehydration occurs when disk space gets low... or directly, when a ENOSPC (no space) error occurs.

**Comment by sanoursa** [comment]
Currently, `gvfs dehydrate` is not smart enough to dehydrate individual files, since doing so is actually rather tricky. The current behavior is rather simple, it just creates a brand new src folder and starts over with a fresh virtualization.

I agree that all of the proposed ideas are good ones, it's just a matter of when they will get prioritized.

**Comment by sanoursa** [comment]
This falls under the scope of better cache management, see #85

**Comment by piranna** [comment]
> This falls under the scope of better cache management, see #85

Fair enought, thanks for point me to the other issue :-)
