### ISSUE TITLE
Unable to mount because the GVFS.Mount process is not responding.

### ISSUE THREAD

**Issue by gcheucn** [Microsoft/GVFS#49]
Recently I am trying GVFS.  It works well on my laptop, but always got below error message on my VM.

__Validating repo...Succeeded
Mounting...Failed. Run 'gvfs log C:\gitRepos\Test' for more info.
Unable_ to mount because the GVFS.Mount process is not responding._

But actually, gvfs status said mount status is ready.
After running  "gvfs unmounts" and "gvfs mount -v Verbose -d" many times, I guess it is due to timeout value in WaitUntilMounted function.

My VM is poor performace. GVFS.Mount process cannot complete task in that timeout. 
I tried to set timeout bigger, rebuilt GVFS. Then, the problem disappeared.

**Comment by sanoursa** [comment]
Thanks for the bug report. We see this every now and then internally as well. It is fairly benign - the core issue is that the background process is not opening its named pipe quickly enough, and the foreground process is timing out, but the mount still succeeds. We do plan to clean this up to open the pipe as quickly as possible, but since most people are running on strong dev machines, this hasn't been a high priority so far.

**Comment by sanoursa** [comment]
I haven't seen any reports of this issue in a long time. Closing it for now.
