### ISSUE TITLE
Option to skip Windows Defender exclusion

### ISSUE THREAD

**Issue by stefanes** [Microsoft/GVFS#57]
We are not using Windows Defender, and it would be nice if there was an option to skip the `Add-MpPreference` call when doing `gvfs mount` (or `gvfs clone` w/out `--no-mount`).

Mount works just fine, but this calls adds unnecessary clutter to the command window/logs.

```
WARNING: Unable to ensure that '<path>' is excluded from antivirus
Could not add this repo to the antivirus exclusion list: Add-MpPreference : Operation failed with the following error: 0x800106b                                                                                                                a. Opera
tion: MpPreference. Target: ConfigListExtension.
At line:1 char:5
+ & { Add-MpPreference -ExclusionPath <path> }
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\
   ...FT_MpPreference) [Add-MpPreference], CimException
    + FullyQualifiedErrorId : HRESULT 0x800106ba,Add-MpPreference

Add-MpPreference : Operation failed with the following error: 0x%1!x!
At line:1 char:5
+ & { Add-MpPreference -ExclusionPath <path> }
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\
   ...FT_MpPreference) [Add-MpPreference], CimException
    + FullyQualifiedErrorId : HRESULT 0x800106ba,Add-MpPreference
```

GVFS version: **1.0.17318.1**
Git version: **2.15.1.gvfs.2.preview.3**

**Comment by sanoursa** [comment]
We've actually taken this Defender exclusion out entirely, since your source control tool shouldn't force any antivirus decision on you. The next release will no longer have this behavior.

The reason this code ever got added in the first place is that very early on, the GvFlt filter driver and Defender's filter driver had conflicts that would lead to system deadlocks, but all such bugs have been fixed so there is no need for this exclusion anymore.

**Comment by damoando4** [comment]
when is the Defender-free version available?
