### ISSUE TITLE
Project dependency PrjFlt is not open-source

### ISSUE THREAD

**Issue by fluffynuts** [Microsoft/GVFS#75]
Having GVFS (or whatever it will be renamed to!) rely on a non-open component (PrjFlt) makes contribution and learning -- two of the greatest parts of open-source -- difficult. The project is managed by this same team, and, although it is marked as pre-release and may perhaps contain some secret sauce which is internal to Microsoft, in the interests of the true spirit of open-source, the source should be made freely available so that anyone wishing to build it for their own system may do so without relying on a binary package at nuget.org.

**Comment by DrorHarari** [comment]
Exactly right and even more so as the specific license used (see https://github.com/Microsoft/GVFS/blob/master/GvFlt_EULA.md) requires you to accept Microsoft sending back home information about your use of the software -- something that reasonable businesses cannot accept.

**Comment by sanoursa** [comment]
While GVFS was in development, we relied on a nuget package containing a prerelease version of GvFlt, the driver that the Windows team was building up for our use. The EULA linked above was for that driver, and quite restrictive because it was prerelease, and not intended for general use yet.

Now the driver has shipped, under the feature name Windows Projected File System, which contains the driver named PrjFlt. This is now part of Windows - any machine that has the April 2018 update now has this driver already available (though it is an optional feature and needs to be enabled).

The statement is accurate that GVFS relies on a non-open component, but that component is now just part of the OS.

For completeness - we still maintain a package on our new myget feed that contains the new PrjFlt driver. The reason for this is that we still have some internal customers who are on machines that have not yet received the April 2018 update. Once all of our customers have moved forward, we will no longer even need that nuget package, and GVFS will just be a user mode application that relies on functionality in the OS.

**Comment by DrorHarari** [comment]
Thanks for that clarification. It would be much better if you update the project Readme.md in the Licenses section where it reads: 

> GVFS relies on the PrjFlt filter driver, formerly known as the GvFlt filter driver, available as a prerelease NuGet package with its 

You can state what you noted above that GVFS relies on Windows starting from some version (10? 2016?) with special package available for older system under specific license.

**Comment by chilinux** [comment]
@sanoursa So this project should be working with Windows 10 Home and Windows 10 LTSB without having to install PrjFlt?  I have developer mode enabled and no pending windows updates but Manage Optional Features does not have a Projected File System option.

**Comment by fluffynuts** [comment]
Also, I'm not sure of the status of that driver or the api it exposes -- but it would be great if the api were documented somewhere for any enthusiastic person to implement on other platforms. Even better would be some motivation to port this to other operating systems (most notably Linux & Mac) -- again, in the interests of fostering the open-source community.
If the original driver were itself open-sourced (or the api well documented and close enough to the metal that any source would mostly be win32 api calls), this would accelerate development for other platforms -- an intrepid person might be able to make enough modifications, for example, to run as a FUSE driver.

**Comment by sanoursa** [comment]
@chilinux The documentation you're looking for is coming. The actual state of the driver is that it is halfway shipped right now. The binary made it into the April 2018 update (version 1803) but the SDK did not (and I should have been more precise, it's a beta release right now). The ProjFS team is doing final API cleanup right now and they expect to ship the SDK with docs and samples in the next Windows release. That said, the GVFS.ProjFS nuget package in the GVFS myget feed does have a well-commented header file and sample code (all of it subject to change still because of the API cleanup that's happening) which you can peruse if you like.

I don't know how to enable optional features via a UI, but to see if you have ProjFS on your machine, you can run the following in Powershell (I ran this on an unmodified Windows 10 version 1803 Azure VM):
```
PS C:\> Get-WindowsOptionalFeature -Online -FeatureName Client-ProjFS

FeatureName      : Client-ProjFS
DisplayName      : Windows Projected File System (Beta)
Description      : Enables Windows Projected File System
RestartRequired  : Possible
State            : Disabled
CustomProperties :
```

There are corresponding `Enable/Disable-WindowsOptionalFeature` commands for turning it on or off. And note that the GVFS installer will also turn it on for you, if it's available.

**Comment by sanoursa** [comment]
@fluffynuts Unfortunately I don't have a say in whether the PrjFlt sources are open sourced, but I discuss it with the ProjFS team every now and then. That being said, we (the GVFS team) are working on porting it over to the Mac, and all of that code _will_ be open source. In fact, the initial versions of it are already working and will be pushed to the repo very soon.

In addition, I'm working on a sample project that implements a cross-platform virtual file system using both the Windows and Mac versions of the ProjFS drivers/APIs. Expect that to be published very soon as well, probably within a couple weeks.

**Comment by sanoursa** [comment]
See #78

**Comment by chilinux** [comment]
Can you add a DLL based interface to the VFS for calling drop in replacements to open, read, write and close functions without needing a kernel space module?

MS WSL still seems to be lacking any method to port linux modules.  While I was never expecting linux modules to work as-is, I was expecting a SDK for porting them at some point.  Instead, the Microsoft stance seem to be under the model of put in a feature request and some months/years later Microsoft may code it for you.

While I understand that WSL is completely outside of the control of the MS GIT team, it would be nice if MS-GVFS had a pure userspace model to help work around the WSL imposed limitations.  The real GVFS (GNOME foundation) has a libgio to provide an alternative to file functions to allow applications that are libgio aware to not require FUSE to access real GVFS.  If MS-GVFS could have it's own libgio style DLL like real GVFS then at least there would be a method of access under a port of MS-GVFS on WSL.

**Comment by sanoursa** [comment]
@chilinux That could definitely be done, but we've had no requests for such functionality from any of the teams using GVFS so I haven't spent any time thinking about it. Please file a new issue for that feature, and describe what problems it solves and what scenarios it will be used in, and we can discuss it there.

(For the record, I have had some requests for a dll to replicate the CLI functionality. Tools do want to programmatically mount/unmount/etc. But we haven't seen any need for a dll to read files, since you can just do so directly out of the file system)

**Comment by paulsapps** [comment]
So still no source for Windows Projected File System? I would like it so that we could try to port to "legacy" Windows versions such as Windows 7..
