### ISSUE TITLE
EEE again ?

### ISSUE THREAD

**Issue by freeseacher** [Microsoft/GVFS#9]
https://en.wikipedia.org/wiki/Embrace,_extend_and_extinguish

**Comment by McNerdius** [comment]
[License.md](https://github.com/Microsoft/GVFS/blob/master/License.md)

**Comment by freeseacher** [comment]
@McNerdius and so ? 
are any pr to git repo itself ? 
public discussion about pros/cons ? 
maillist's activity ? 

as far as i can see no. just another kind of `product`. 
that extends standart and helps users move to win10.

**Comment by sanoursa** [comment]
All of our changes to git are available here: https://github.com/Microsoft/git/tree/gvfs. Public discussions are ongoing, e.g. here: https://public-inbox.org/git/20170113155253.1644-1-benpeart@microsoft.com/T/#u.

**Comment by cornerot** [comment]
https://github.com/Microsoft/GVFS/blob/master/GvFlt_EULA.docx
"You may install and use any number of copies of the software on your devices, solely for use with Microsoft Git Virtual File System (GVFS) and otherwise for your internal business purposes. You may not use the software in a live operating environment unless Microsoft permits you to do so under another agreement."

"The software may collect information about you and your use of the software and send that to Microsoft. Microsoft may use this information to provide services and improve Microsoft’s products and services. Your opt-out rights, if any, are described in the product documentation."

**Comment by DominikDitoIvosevic** [comment]
How can it be both MIT and with this restrictive license?

**Comment by sanoursa** [comment]
To be clear, the GvFlt_EULA applies to the GvFlt filter driver, which is currently only available as a preview. All of the GVFS source code is available under the MIT license. We will have more to say soon about how GvFlt will be released once it is ready.
